# Generated by Django 5.2.3 on 2025-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
