# Generated by Django 5.2.3 on 2025-06-21 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_forms', '0002_firstmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_sh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_sh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_sh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OtdelSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otdel_sh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanBuyCarsVactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_cars', models.IntegerField()),
                ('vacations', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count_vacancy_buy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('budget_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.budgetowner')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.company')),
                ('company_sh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.companysh')),
                ('department_sh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.departmentsh')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.grade')),
                ('group_sh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.groupsh')),
                ('otdel_sh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.otdelsh')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.period')),
                ('type_car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.carclass')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_budget', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_budget', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FirstModel',
        ),
        migrations.AddField(
            model_name='planbuycarsvactionsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.post'),
        ),
        migrations.AddField(
            model_name='planbuycarsvactionsmodel',
            name='scenario_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.scenariobudget'),
        ),
        migrations.AddField(
            model_name='planbuycarsvactionsmodel',
            name='type_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_forms.typebudget'),
        ),
    ]
