# Generated by Django 5.2.3 on 2025-06-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_forms', '0003_budgetowner_carclass_company_companysh_departmentsh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbuycarsvactionsmodel',
            name='period',
            field=models.DateField(),
        ),
    ]
