# Generated by Django 5.2.3 on 2025-06-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_forms', '0004_alter_planbuycarsvactionsmodel_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
