services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_app
    env_file:
      - ./.prod.env

  django_app:
    build: .
    image: django_app
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - django_app

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    networks:
      - django_app

volumes:
  postgres_data:


networks:
  django_app:
